FROM python:3.11

WORKDIR /app

ENV PIP_DISABLE_PIP_VERSION_CHECK=on

# Instaling dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Installing aplication
COPY ./src ./src
COPY ./pyproject.toml ./
RUN pip install . --no-deps

EXPOSE 8501

RUN chmod -R a+x .

CMD ["bot", "frontend", "start"]