FROM jupyter/minimal-notebook

WORKDIR /project

COPY ./notebooks /project/notebooks
COPY ./src /project/src
COPY ./pyproject.toml /project/pyproject.toml
COPY ./README.md /project/README.md
COPY ./LICENSE.txt /project/LICENSE.txt
COPY ./docker/pyodbc.sh /project/pyodbc.sh

USER root

RUN bash /project/pyodbc.sh

RUN pip install .

RUN python -c "from langchain.embeddings import HuggingFaceEmbeddings; embeddings = HuggingFaceEmbeddings(model_name='clips/mfaq')"

ENV PIP_DISABLE_PIP_VERSION_CHECK=on

RUN chmod +777 -R /home/jovyan

EXPOSE 8888

VOLUME /project

CMD ["start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.password=''", "--NotebookApp.default_url='/lab/tree'", "--notebook-dir=/project/notebooks"]
