FROM python:3.11

WORKDIR /app

ENV PIP_DISABLE_PIP_VERSION_CHECK=on

COPY ./src ./src
COPY ./pyproject.toml ./
RUN pip install .

EXPOSE 8501

RUN chmod -R a+x .

CMD ["bot", "frontend", "start"]